### ISSUE TITLE
Umi without anime embeds?

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Klokinator/UnivAICharGen#24]
I appreciate the new functionalities to the wildcard system, but I don't understand why this comes with nearly 900 anime character embeddings and a bunch of porn wildcards?

I mean, I do understand it, but wouldn't it make more sense to have that as an opt-in thing?

**Comment by I-ShadowStar** [comment]
When UmiAI was initially conceived, there were no good repository sites, and Embeddings were all the rage. The included collection was intended to preserve all those character and other embeddings for the community. Since then, sites like Civitai have come up and we no longer have to worry so much about 'losing' good models, as well as new variations of LoRA models making Embeddings much less popular.

I've been told that in the next version of UmiAI, they are considering removing the included embeds and either setting them up as a stand-alone "DLC" like package, or possibly not including it at all since it's easy enough now to get all the extra model related stuff you could want.

**Comment by MNeMoNiCuZ** [comment]
That sounds like a good idea.
I think it's a nice collection and all, but it's just so weird to have it bundled with an extension that has other functionality.

In the end I went back to DynamicPrompts. Even if it's not updated in a long while, it was less frustrating and more up-front with stuff.

But this extension could easily break it. Ideally though with a name change that makes sense too ^^

**Comment by ctwrs** [comment]
@MNeMoNiCuZ you can use the wildcards by themselves at https://github.com/Klokinator/Umi-AI-Wildcards

**Comment by rubenssoto** [comment]
@ctwrs can I install Umi AI from https://github.com/Klokinator/Umi-AI-Wildcards? I don´t want the embeeds too

**Comment by I-ShadowStar** [comment]
> @ctwrs can I install Umi AI from https://github.com/Klokinator/Umi-AI-Wildcards? I don´t want the embeds too

Yes, that is the exact intention of that version, not including all those embeddings. ;)
